### ISSUE TITLE
Não Consigo Fazer o Login

### ISSUE THREAD

**Issue by Evander12** [BrunoMCarnauba/sistema_restaurante#1]
Bom dia!

Queria tirar uma duvida com voce, criei um usuario direto na base pois nao consegui logar no usuario admin@admin

porém após criar o usuario tbm não foi possivel efetuar login, só diz que foi erro de senha, consegue me auxiliar ?

**Comment by BrunoMCarnauba** [comment]
Olá, @Evander12 !
Acho que você está falando do sistema web, né?
Acredito que você já rodou pelo terminal o comando "php artisan migrate" na pasta raíz do sistema web pra criar as tabelas e colunas do banco de dados.

Lá na pasta web_api/database/seeds contém os arquivos que são responsáveis por gravar no banco os dados pra o primeiro uso do sistema. São os chamados Seeders. O arquivo FuncionariosSeeder.php é responsável por criar a primeira autenticação com o e-mail "admin@admin.com" e senha "123456" na tabela "funcionarios" do banco de dados. Eles são executados quando você roda pelo terminal o comando "php artisan db:seed" na pasta raíz do sistema web. É importante rodar esse comando, pq ele tbm grava os cargos, mesas e categorias.

Quando você tenta se autenticar é chamado o método "logar" do arquivo web_api/app/Http/Controllers/LoginController. Esse método pega o que foi informado nos campos da tela e chama o método "autenticar" do arquivo web_api/app/Models/Funcionario.php que é responsável pela consulta no banco de dados. A validação é bem simples, ele libera o acesso se encontrar na tabela funcionarios o cadastro que tenha o e-mail e senha informado, sem outras validações.

Então pra tá dando o erro "Login ou Senha incorreta", realmente ele não está encontrando a informação no banco.
Você colocou "admin@admin" ou "admin@admin.com"? O que é gravado pelo Seeder é esse segundo. Caso ainda não funcione, tenta apagar o banco de dados, criar novamente e rodar os comandos "php artisan migrate" e depois "php artisan db:seed". Ai usa a autenticação "admin@admin.com" e senha "123456".

Espero que funcione. Valeu!
No readme.md tem mais detalhes: https://github.com/BrunoMCarnauba/sistema_restaurante/blob/master/readme.md
